version: "3.9"

services:
  cdn:
    container_name: local_cdn
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - TZ=UTC
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 3s
      retries: 5
    restart: unless-stopped
